###
GET http://localhost:3000/api/users

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "firstName": "   ds      dqwdqd",
    "lastName":"2eww ",   
    "userName": "o_esssahan",
    "email": "Virginssie@Feesthotmail.com",
    "password": "*2sfdfqs",
    "tel": "5948077100"
}

### 
GET http://localhost:3000/api/users/5ff0e943e5e8c20ae47d38fd

### 
DELETE  http://localhost:3000/api/users/5ff390f134d1d534c4914a0a



###
PUT http://localhost:3000/api/users/5ff0e943e5e8c20ae47d38fd
Content-Type: application/json

{
    "fritsName": "Oliver 2"
}